### ISSUE TITLE
Duplicate modsecurity alert on `proxy_pass` use case

### ISSUE THREAD

**Issue by h3ph4est7s** [flo-mic/secure-proxy#4]
**Describe the bug**
There is a duplicate `modsecurity` error log entry when a `proxy_pass` directive is used for a site. Thus resulting into excessive log entries and `fail2ban` malfunction by banning hosts at half the tries.

**Current environment**
- Architecture: amd64
- Container Version:  'latest'
- Docker Version:  '20.10.7'

**To Reproduce**
1. Add a proxy site block to `/config/nginx/sites-available` i.e.
```nginx
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	server_name api.example.com;

       # include site related configurations like ssl, error pages, robots, deny list and geoip
	include /config/nginx/sites-conf.d/acme.conf;
	include /config/nginx/sites-conf.d/deny-rules.conf;
	include /config/nginx/sites-conf.d/error-pages.conf;
	include /config/nginx/sites-conf.d/geoip.conf;
	include /config/nginx/sites-conf.d/robots.conf;
	include /config/nginx/sites-conf.d/ssl.conf;

    location / {
		return 404;
	}

    location ^~/v1/ {
        proxy_pass         http://api:8000/;
    }
}
```
2. Navigate to the proxy url and try an "attack" i.e. `?asdf=../../../etc/passwd`

**Expected behavior**
To create only one entry per event.

**Screenshots**
N/A

**Log files**
```log
2022/01/04 16:20:24 [error] 8277#8277: *18 [client 192.168.224.1] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `30' ) [file "/config/nginx/modsec.d/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 30)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.224.2"] [uri "/v1/11"] [unique_id "1641306024"] [ref ""], client: 192.168.224.1, server: api.example.com, request: "GET /v1/11?asdf=../../../etc/passwd HTTP/2.0", host: "api.example.com"

2022/01/04 16:20:24 [error] 8277#8277: *18 [client 192.168.224.1] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `30' ) [file "/config/nginx/modsec.d/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 30)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.224.2"] [uri "/v1/11"] [unique_id "1641306024"] [ref ""], client: 192.168.224.1, server: api.example.com, request: "GET /v1/11?asdf=../../../etc/passwd HTTP/2.0", host: "api.example.com"
```

**Additional context**
This problem does not replicate for the default block.

**Comment by flo-mic** [comment]
Hmm thats interesting. I noticed such a behavior also on my dev system. I thought this was because i send some HTTP Get to an listed HSTS preload domain (which i use for testing)

Will have a look on this tomorrow with another test domain without HSTS preload.

**Comment by h3ph4est7s** [comment]
Yeah its bugging me for some time now. This is replicable with curl though... (i thought that my browser was doing its "magic" again)

**Comment by h3ph4est7s** [comment]
The initial hypothesis was taking into consideration that the problem is related to duplicate request parsing from `modsecurity` thus resulting to duplicate error log entries. After https://github.com/flo-mic/secure-proxy/pull/5#issuecomment-1005748204 i have strong suspicions that the impact is expanded `nginx` wide. All the request hooks are executed **2** times for each request including `crowdsec` and any possibly other `nginx` module.  The performance impact of that is proportionally bigger compared to the initial and should be addressed before any heavy production use.

**Comment by flo-mic** [comment]
@h3ph4est7s I fixed the related issue. The issue was caused by the custom error page. The custom error page was flagged as `internal` as no one should be able to access this manually. However, during the internal redirect from a blocked request to the error page, the request was processed again by crowdsec and modsecurity. 

Additionally the error page also contained a line which caused this page to reload itself one time. Both misconfigurations in combination caused up to 4 redirects on the error page. The fix is currently building and will be ready in ca. 10 minutes (https://github.com/flo-mic/secure-proxy/actions/runs/1663599598)

Please delete the existing error.html file as well as the error-pages.conf and test again
